language: bash

services:
- docker

script:
- docker login --username $ALI_USERNAME http://114.115.138.52 --password $ALI_PASSWORD
- docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
- bash push-images.sh
