language: bash

services:
- docker

script:
- docker login --username $ALI_USERNAME registry.cn-hangzhou.aliyuncs.com --password $ALI_PASSWORD
- docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
- bash push-images.sh
